# windows.yml 

name: Windows
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2  
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Project
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake .
          cmake --build .
